export const ventArray = [13, 22, 61,70, 121, 130]
export const initialLayout = [
 
    { id:0,
      position:1,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:1,
      position:2,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:2,
      position:3,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:3,
      position:4,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:4,
      position:5,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:5,
      position:6,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:6,
      position:7,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:7,
      position:8,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:8,
      position:9,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:9,
      position:10,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:10,
      position:11,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:11,
      position:12,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:12,
      position:13,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:13,
      position:14,
      contents:"",
      defaultContents:"",
      background:"fog vent"
    },
    { id:14,
      position:15,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:15,
      position:16,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:16,
      position:17,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:17,
      position:18,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:18,
      position:19,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:19,
      position:20,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:20,
      position:21,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:21,
      position:22,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:22,
      position:23,
      contents:"",
      defaultContents:"",
      background:"fog vent"
    },
    { id:23,
      position:24,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:24,
      position:25,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:25,
      position:26,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:26,
      position:27,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:27,
      position:28,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:28,
      position:29,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:29,
      position:30,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:30,
      position:31,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:31,
      position:32,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:32,
      position:33,
      contents:"player",
      defaultContents:"",
      background:""
    },
    { id:33,
      position:34,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:34,
      position:35,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:35,
      position:36,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:36,
      position:37,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:37,
      position:38,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:38,
      position:39,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:39,
      position:40,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:40,
      position:41,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:41,
      position:42,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:42,
      position:43,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:43,
      position:44,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:44,
      position:45,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:45,
      position:46,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:46,
      position:47,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:47,
      position:48,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:48,
      position:49,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:49,
      position:50,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:50,
      position:51,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:51,
      position:52,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:52,
      position:53,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:53,
      position:54,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:54,
      position:55,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:55,
      position:56,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:56,
      position:57,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:57,
      position:58,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:58,
      position:59,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:59,
      position:60,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:60,
      position:61,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:61,
      position:62,
      contents:"",
      defaultContents:"",
      background:"fog vent"
    },
    { id:62,
      position:63,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:63,
      position:64,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:64,
      position:65,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:65,
      position:66,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:66,
      position:67,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:67,
      position:68,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:68,
      position:69,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:69,
      position:70,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:70,
      position:71,
      contents:"",
      defaultContents:"",
      background:"fog vent"
    },
    { id:71,
      position:72,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:72,
      position:73,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:73,
      position:74,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:74,
      position:75,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:75,
      position:76,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:76,
      position:77,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:77,
      position:78,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:78,
      position:79,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:79,
      position:80,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:80,
      position:81,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:81,
      position:82,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:82,
      position:83,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:83,
      position:84,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:84,
      position:85,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:85,
      position:86,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:86,
      position:87,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:87,
      position:88,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:88,
      position:89,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:89,
      position:90,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:90,
      position:91,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:91,
      position:92,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:92,
      position:93,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:93,
      position:94,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:94,
      position:95,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:95,
      position:96,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:96,
      position:97,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:97,
      position:98,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:98,
      position:99,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:99,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:100,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:101,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:102,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:103,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:104,
      position:100,
      contents:"computer",
      defaultContents:"",
      background:"fog"
    },
    { id:105,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:106,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:107,
      position:100,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:108,
      position:100,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:109,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:110,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:111,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:112,
      position:100,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:113,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:114,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:115,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:116,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:117,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:118,
      position:100,
      contents:"computer",
      defaultContents:"",
      background:"fog"
    },
    { id:119,
      position:100,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:120,
      position:100,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:121,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog vent"
    },
    { id:122,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:123,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:124,
      position:100,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:125,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:126,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:127,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:128,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:129,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog"
    },
    { id:130,
      position:100,
      contents:"",
      defaultContents:"",
      background:"fog vent"
    },
    { id:131,
      position:100,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:132,
      position:100,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:133,
      position:100,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:134,
      position:100,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:135,
      position:100,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:136,
      position:100,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:137,
      position:100,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:138,
      position:100,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:139,
      position:100,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:140,
      position:100,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:141,
      position:100,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:142,
      position:100,
      contents:"wall",
      defaultContents:"",
      background:""
    },
    { id:143,
      position:100,
      contents:"wall",
      defaultContents:"",
      background:""
    }
  
]